; CacaoSense - cacao-02-lote2-wokwi (ESP32 simulado con Wokwi for VS Code)
[env:esp32dev]
platform = espressif32@7.1.2
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  knolleary/PubSubClient@^2.8
  bblanchon/ArduinoJson@^6.21.5
  adafruit/DHT sensor library@^1.4.6
  adafruit/Adafruit Unified Sensor@^1.1.14
